<?php
$current = json_decode(file_get_contents('c:/Bola/Clinova/lang/ar.json'), true);

$missing = [
    "Smart Clinic Management" => "إدارة العيادة الذكية",
    "Clinova — Smart Clinic Platform" => "كلينوفا — منصة العيادة الذكية",
    "Manage Your Clinic" => "أدر عيادتك",
    "Smarter. Faster. Better." => "بذكاء. بسرعة. باحترافية.",
    "Smarter" => "بذكاء",
    "How It Works" => "كيف تعمل",
    "See How It Works" => "شاهد كيف تعمل",
    "How to get started" => "كيف تبدأ",
    "with Clinova?" => "مع كلينوفا؟",
    "Testimonials" => "آراء الأطباء",
    "What doctors say" => "ماذا يقول الأطباء",
    "about Clinova" => "عن كلينوفا",
    "Limited Time Offer" => "عرض لفترة محدودة",
    "Ready to transform" => "مستعد لتحويل",
    "your clinic?" => "عيادتك؟",
    "Join hundreds of doctors who already use Clinova to deliver better care, faster." => "انضم لمئات الأطباء الذين يستخدمون كلينوفا لتقديم رعاية أفضل، وأسرع.",
    "Sign In" => "تسجيل الدخول",
    "All systems operational" => "جميع الأنظمة تعمل بشكل طبيعي",
    "Trusted by leading clinics and medical centers" => "موثوق به من قِبل العيادات ومراكز طبية رائدة",
    "Why Clinova?" => "لماذا كلينوفا؟",
    "Your Vision," => "رؤيتك،",
    "Our Platform." => "منصتنا.",
    "Clinova was built from the ground up by a team of developers working closely with real doctors. Every feature is designed to minimize admin work and maximize time with patients." => "بُنيت كلينوفا من الصفر بواسطة فريق من المطورين يعملون عن كثب مع أطباء حقيقيين. كل ميزة مصممة لتقليل العمل الإداري وزيادة وقتك مع المرضى.",
    "Instant Setup" => "إعداد فوري",
    "Get your clinic online in under 10 minutes. No IT team needed." => "احصل على عيادتك أونلاين في أقل من 10 دقائق. لا تحتاج لفريق تقني.",
    "Arabic & English" => "عربي وإنجليزي",
    "Full bilingual support with proper RTL layout for Arabic users." => "دعم كامل للغتين مع تخطيط RTL صحيح للمستخدمين العرب.",
    "Multi-Doctor Support" => "دعم عدة أطباء",
    "Manage multiple doctors, schedules, and independent income reports." => "أدر عدة أطباء، جداول زمنية، وتقارير دخل مستقلة.",
    "Simple Process" => "عملية بسيطة",
    "Core Modules" => "الوحدات الأساسية",
    "Everything you need to run" => "كل ما تحتاجه لإدارة",
    "a successful practice" => "ممارسة طبية ناجحة",
    "Designed by medical professionals for efficiency and clinical excellence." => "مصمم بواسطة متخصصين طبيين للكفاءة والتميز السريري.",
    "Multi-Role Access" => "صلاحيات متعددة",
    "Doctor, Secretary, and Admin roles — each with a tailored dashboard, permissions, and workflow." => "أدوار الطبيب، السكرتيرة، والمدير — كل منها بلوحة تحكم مخصصة, صلاحيات, وسير عمل.",
    "Patient Profiles" => "ملفات المرضى",
    "Complete patient history, visit records, medical files, tags, and rapid booking — all in one place." => "تاريخ المريض الكامل، سجلات الزيارات، الملفات الطبية، التاقات، والحجز السريع — كل ذلك في مكان واحد.",
    "Secure & Reliable" => "آمن وموثوق",
    "Enterprise-grade security with encrypted data storage, role-based access, and 99.9% uptime guarantee." => "أمان على مستوى المؤسسات مع تخزين بيانات مشفر، وصول قائم على الأدوار، وضمان تشغيل 99.9%.",
    "Why Clinova?" => "لماذا كلينوفا؟",
    "Feature Overview" => "نظرة عامة على الميزات",
    "Appointments Today" => "المواعيد اليوم",
    "Monthly Revenue" => "الإيراد الشهري",
    "Medical Center" => "مركز طبي",
    "Booked" => "محجوز",
    "Create Your Account" => "إنشاء حسابك",
    "Register in seconds. No credit card required. Set up your clinic profile with your name, specialty, and fees." => "سجّل في ثوانٍ. لا حاجة لبطاقة ائتمانية. أنشئ ملف عيادتك باسمك وتخصصك ورسومك.",
    "Customize Your Settings" => "تخصيص إعداداتك",
    "Configure your consultation fees, add doctors and secretary accounts, and personalize the system to your workflow." => "اضبط رسوم الاستشارة، أضف حسابات الأطباء والسكرتيرة، وخصص النظام لتناسب سير عملك.",
    "Add Patients & Book Appointments" => "إضافة مرضى وحجز مواعيد",
    "Start adding patient records and booking appointments. The system handles the waitlist, visit records, and billing automatically." => "ابدأ بإضافة سجلات المرضى وحجز المواعيد. النظام يدير الحجوزات وسجلات الزيارات والفوترة تلقائياً.",
    "Track & Grow" => "تتبع ونمو",
    "Monitor your clinic performance, revenue trends, and patient statistics from a beautiful analytics dashboard." => "راقب أداء عيادتك واتجاهات الإيرادات وإحصائيات المرضى من لوحة تحليلات جميلة.",
    "General Practitioner" => "طبيب عام",
    "Pediatrician" => "طبيب أطفال",
    "Orthopedic Surgeon" => "جراح عظام",
    "Clinova completely transformed how I run my clinic. The waitlist management is flawless, and patients love the experience." => "كلينوفا غيرت بشكل كامل طريقة إدارة عيادتي. إدارة الحجوزات مثالية، والمرضى يحبون التجربة.",
    "The Arabic interface is perfect. My team adapted to it instantly. The financial reports save me hours every month." => "الواجهة العربية مثالية. استوعبها فريقي فوراً. التقارير المالية توفر عليّ ساعات كل شهر.",
    "I manage 3 doctors in my clinic now. Clinova handles all the complexity—separate income, separate waitlists—effortlessly." => "أدير الآن 3 أطباء في عيادتي. كلينوفا تتعامل مع كل التعقيدات — دخل منفصل، حجوزات منفصلة — بكل سهولة.",
    "Transforming medical practice management with modern technology." => "تحويل إدارة الممارسة الطبية بالتكنولوجيا الحديثة.",
    "How It Works" => "كيف تعمل",
    "Testimonials" => "آراء الأطباء",
    "All rights reserved." => "جميع الحقوق محفوظة.",
    "Roadmap" => "خارطة الطريق",
    "Careers" => "وظائف",
    "GDPR" => "اللائحة الأوروبية",
    "Blog" => "المدونة",
    "Introducing Clinova 2.0" => "نقدم كلينوفا 2.0",
    "Doctors" => "طبيب",
    "Uptime" => "وقت التشغيل",
];

foreach ($missing as $key => $value) {
    $current[$key] = $value;
}

ksort($current);

file_put_contents('c:/Bola/Clinova/lang/ar.json', json_encode($current, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));
echo "Landing page localization completed\n";
